# Плагин "InfernWarp" Версия плагина: 1.0.0v
# Разработчик (По всем вопросам) -> Егор Татаркин (Ник в майне: EG_SH_NOT) vk.com/egortatarkin : @theegorhick (Telegram)

# Мой Канал тг (буду благодарен подписке :))) : Канал Великого Егшота -> t.me/egashotina

# Сообщение
message:
  set-warp: "§x§F§B§D§7§0§8▶§f Варп §x§F§B§D§7§0§8установлен! "
  del-warp: "§x§f§d§0§0§0§0▶§f Варп §x§f§d§0§0§0§0удален!"
  teleport: "§x§F§B§D§7§0§8▶ Телепортируемся.... "
  limit-warps: "§x§f§d§0§0§0§0▶§f Вы достигли §x§f§d§0§0§0§0лимита§f установки варпов! "
  del-not-perms: "§x§f§d§0§0§0§0▶ Нет прав!"
  warp-not-found: "§x§f§d§0§0§0§0▶§f Варп не §x§f§d§0§0§0§0найден! "
  warp-not-name: "§x§f§d§0§0§0§0▶§f Укажите имя §x§f§d§0§0§0§0варпа"
  warp-not-teleport: "§x§f§d§0§0§0§0▶§f Такой варп уже §x§f§d§0§0§0§0существует! "
# Настройка
limits: # лимит, право: infernwarp.setwarp.(название группы)
  default: 1 # Название группы: Кол-во